name = "CobbleWeones"
author = "Chesare"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f4efec3d335e36ecc8ec24a8bd3a5f204fcd589732a66362d8fb8f19cfd98c0"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
