name = "CobbleWeones"
author = "TChesare"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd798a12a184ba39f7ffef940314c61ebc9a52bf83440bcfcb70015629efec40"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
