name = "CobbleWeones"
author = "TChesare"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52ed75a94fd6d53c9b27ac0735b5a32b0c95602d852d9f5638a0ece4612d20ee"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
